### ISSUE TITLE
projective transformation 

### ISSUE THREAD

**Issue by liyingliu** [yuliangguo/3D_Lane_Synthetic_Dataset#1]
Hi @yuliangguo ,

Thanks for the amazing work!
Could you clarify the projective transformation of the second stage network in the paper is done by a spatial transformer network or just a homography? If it’s done by a spatial transformer module, could you explain a bit more about the reason? Since it’s a two-stage network, I guess a spatial transformer module is not necessary? Thanks in advance!

**Comment by yuliangguo** [comment]
> Hi @yuliangguo ,
> 
> Thanks for the amazing work!
> Could you clarify the projective transformation of the second stage network in the paper is done by a spatial transformer network or just a homography? If it’s done by a spatial transformer module, could you explain a bit more about the reason? Since it’s a two-stage network, I guess a spatial transformer module is not necessary? Thanks in advance!

Thank you for the question. You are right that the spatial transform module is not very necessury for the two-stage framework. It could be replaced with a homography of the segmentation map. We chose to keep it in our network to gareentee the flexibility in applying transfer learning or end-to-end training schemes with intermediate supervision.

**Comment by liyingliu** [comment]
Thanks for the prompt reply. By the way, is the geometric transformation at the end of the second stage also done by homography? With the camera intrinsic and extrinsic, we should be able to convert anchor in virtual top-view into the ego-vehicle coordinate system, right?

**Comment by yuliangguo** [comment]
> Thanks for the prompt reply. By the way, is the geometric transformation at the end of the second stage also done by homography? With the camera intrinsic and extrinsic, we should be able to convert anchor in virtual top-view into the ego-vehicle coordinate system, right?

The final transformation is not strictly a homography because there are 3D coordinates involved. The transformation is derived in the paper and in a concise form. Please refer to the paper for the formular.

**Comment by yuliangguo** [comment]
Btw, I think further discussion here is rather beyond the scope of dataset
issue. Please feel free to send me an email to follow up. I can also inform
you as soon as my method code is released.

**Comment by yuliangguo** [comment]
> Thanks for the prompt reply. By the way, is the geometric transformation at the end of the second stage also done by homography? With the camera intrinsic and extrinsic, we should be able to convert anchor in virtual top-view into the ego-vehicle coordinate system, right?

Btw, I think further discussion is rather beyond the scope of dataset issue. Please feel free to send me an email to follow up. I can also inform you as soon as my method code is released.
